stages:
  process_data:
    cmd: python src/preprocessing/preprocessing_data.py
    deps:
    - data/test.tsv
    - data/train.tsv
    - data/validation.tsv
    - src/preprocessing/preprocessing_data.py
    outs:
    - output/text_processing_test.joblib
    - output/text_processing_train.joblib
    - output/text_processing_val.joblib
  transform_mybag:
    cmd: python src/transformation/transformer_mybag.py
    deps:
    - output/text_processing_train.joblib
    - output/text_processing_val.joblib
    - src/transformation/transformer_mybag.py
    outs:
    - output/mybag_tags_counts.joblib
    - output/mybag_words_counts_val.joblib
    - output/transform_mybag_train.joblib
    - output/transform_mybag_val.joblib
  transform_tfidf:
    cmd: python src/transformation/transformer_tfidf.py
    deps:
    - output/text_processing_train.joblib
    - output/text_processing_val.joblib
    - src/transformation/transformer_tfidf.py
    outs:
    - output/tfidf_tags_counts.joblib
    - output/tfidf_tags_counts_val.joblib
    - output/transform_tfidf_train.joblib
    - output/transform_tfidf_val.joblib
  train:
    cmd: python src/classification/train.py
    deps:
    - output/mybag_tags_counts.joblib
    - output/tfidf_tags_counts.joblib
    - output/transform_mybag_train.joblib
    - output/transform_tfidf_train.joblib
    - src/classification/train.py
    outs:
    - output/mlb_mybag_dvc.joblib
    - output/mlb_tfidf_dvc.joblib
    - output/model_mybag_dvc.joblib
    - output/model_tfidf_dvc.joblib
  evaluate_mybag:
    cmd: python src/evaluation/evaluate_mybag.py
    deps:
    - output/mlb_mybag_dvc.joblib
    - output/model_mybag_dvc.joblib
    - output/transform_mybag_val.joblib
    - src/evaluation/evaluate_mybag.py
    outs:
    - output/y_val_predicted_scores_labels_mybag.joblib
    - output/y_val_predicted_scores_mybag.joblib
  evaluate_tfidf:
    cmd: python src/evaluation/evaluate_tfidf.py
    deps:
    - output/mlb_tfidf_dvc.joblib
    - output/model_tfidf_dvc.joblib
    - output/transform_tfidf_val.joblib
    - src/evaluation/evaluate_tfidf.py
    outs:
    - output/y_val_predicted_labels_tfidf.joblib
    - output/y_val_predicted_scores_tfidf.joblib
