{
 "title": "Dashboardv4",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Model Comparissons and General Summaries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Accuracy Comparisson",
   "type": "timeseries",
   "description": "The equation used is \n(mybag correct times)/(mybag correct times + mybag incorrect times)",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100*totalMybagCorrectTimes/(totalMybagCorrectTimes+totalMybagIncorrectTimes)",
     "legendFormat": "{{Bag-of-words}}"
    },
    {
     "expr": "100*totalTfidfCorrectTimes/(totalTfidfCorrectTimes+totalTfidfIncorrectTimes)",
     "legendFormat": "{{TF-IDF}}"
    }
   ]
  },
  {
   "title": "Tag distribution over the three categories",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "targets": [
    { "expr": "tagMetric" }
   ]
  },
  {
   "title": "Amount of missed labels (included bty the user)",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 6 },
   "targets": [
    {
     "expr": "tagMetric{correctness=\"missed\", model=\"both\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bag-of-words Model",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of correct Bag-of-Words prediction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      { "expr": "totalMybagCorrectTimes" }
     ]
    },
    {
     "title": "Training Stats Bag-of-Words",
     "type": "text",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 16 },
     "options": {
      "content": "## Performance achived during training\n\n### Accuracy score:  0.36\n### Precision score:  0.81\n### Recall score:  0.56\n### F1 score:  0.66\n### Average precision score:  0.36"
     },
     "targets": [
      { "expr": "21" },
      { "expr": "totalTfidfCorrectTimes" }
     ]
    },
    {
     "title": "Tags distribution (Bag-of-words)",
     "type": "table",
     "gridPos": { "h": 16, "w": 7, "x": 17, "y": 16 },
     "targets": [
      {
       "expr": "tagMetric{correctness=\"correct\"}"
      },
      {
       "expr": "tagMetric{correctness=\"incorrect\"}"
      }
     ]
    },
    {
     "title": "Accuracy",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "totalMybagCorrectTimes/(totalMybagCorrectTimes+totalMybagIncorrectTimes)"
      }
     ]
    },
    {
     "title": "Accuracy of Bag-of-words Classifier",
     "type": "timeseries",
     "description": "The equation used is \n(mybag correct times)/(mybag correct times + mybag incorrect times)",
     "gridPos": { "h": 8, "w": 13, "x": 4, "y": 24 },
     "targets": [
      {
       "expr": "totalMybagCorrectTimes/(totalMybagCorrectTimes+totalMybagIncorrectTimes)"
      }
     ]
    },
    {
     "title": "Precision",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mybagPrecision" }
     ]
    },
    {
     "title": "Precision history of Bag-of-words Classifier",
     "type": "timeseries",
     "description": "The equation used is \n(mybag correct times)/(mybag correct times + mybag incorrect times)",
     "gridPos": { "h": 8, "w": 13, "x": 4, "y": 32 },
     "targets": [
      { "expr": "mybagPrecision" }
     ]
    },
    {
     "title": "Recall",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mybagRecall" }
     ]
    },
    {
     "title": "Recall history of Bag-of-words Classifier",
     "type": "timeseries",
     "description": "The equation used is \n(mybag correct times)/(mybag correct times + mybag incorrect times)",
     "gridPos": { "h": 8, "w": 13, "x": 4, "y": 40 },
     "targets": [
      { "expr": "mybagRecall" }
     ]
    },
    {
     "title": "F1 score",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mybagF1" }
     ]
    },
    {
     "title": "F1 score history of Bag-of-words Classifier",
     "type": "timeseries",
     "description": "The equation used is \n(mybag correct times)/(mybag correct times + mybag incorrect times)",
     "gridPos": { "h": 8, "w": 13, "x": 4, "y": 48 },
     "targets": [
      { "expr": "mybagF1" }
     ]
    }
   ]
  },
  {
   "title": "TF-IDF Model",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Correct TFIDF Prediction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      { "expr": "totalTfidfCorrectTimes" }
     ]
    },
    {
     "title": "Training Stats TF-IDF",
     "type": "text",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 17 },
     "options": {
      "content": "## Performance achieved during training\n\n### Accuracy score:  0.37\n### Precision score:  0.83\n### Recall score:  0.55\n### F1 score:  0.65\n### Average precision score:  0.35"
     },
     "targets": [
      { "expr": "21" },
      { "expr": "totalTfidfCorrectTimes" }
     ]
    },
    {
     "title": "Tag distribution (TF-IDF)",
     "type": "table",
     "gridPos": { "h": 16, "w": 7, "x": 17, "y": 17 },
     "targets": [
      {
       "expr": "tagMetric{correctness=\"correct\"}"
      },
      {
       "expr": "tagMetric{correctness=\"incorrect\"}"
      }
     ]
    },
    {
     "title": "Accuracy",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "totalTfidfCorrectTimes/(totalTfidfCorrectTimes+totalTfidfIncorrectTimes)"
      }
     ]
    },
    {
     "title": "Accuracy history of TF-IDF Classifier",
     "type": "timeseries",
     "description": "The equation used to calculate the accuracy of tfidf classifier is (tfidf correct times)/(tfidf correct times + tfidf incorrect times)",
     "gridPos": { "h": 8, "w": 13, "x": 4, "y": 25 },
     "targets": [
      {
       "expr": "totalTfidfCorrectTimes/(totalTfidfCorrectTimes+totalTfidfIncorrectTimes)"
      }
     ]
    },
    {
     "title": "Precision",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "tfidfPrecision" }
     ]
    },
    {
     "title": "Precision history of TF-IDF Classifier",
     "type": "timeseries",
     "description": "The equation used to calculate the accuracy of tfidf classifier is (tfidf correct times)/(tfidf correct times + tfidf incorrect times)",
     "gridPos": { "h": 8, "w": 13, "x": 4, "y": 33 },
     "targets": [
      { "expr": "tfidfPrecision" }
     ]
    },
    {
     "title": "Recall",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "tfidfRecall" }
     ]
    },
    {
     "title": "Recall history of TF-IDF Classifier",
     "type": "timeseries",
     "description": "The equation used to calculate the accuracy of tfidf classifier is (tfidf correct times)/(tfidf correct times + tfidf incorrect times)",
     "gridPos": { "h": 8, "w": 13, "x": 4, "y": 41 },
     "targets": [
      { "expr": "tfidfRecall" }
     ]
    },
    {
     "title": "F1 score",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "tfidfF1" }
     ]
    },
    {
     "title": "F1 score history of TF-IDF Classifier",
     "type": "timeseries",
     "description": "The equation used to calculate the accuracy of tfidf classifier is (tfidf correct times)/(tfidf correct times + tfidf incorrect times)",
     "gridPos": { "h": 8, "w": 13, "x": 4, "y": 49 },
     "targets": [
      { "expr": "tfidfF1" }
     ]
    }
   ]
  }
 ]
}